const official = 'https://www.hansungchurch.com';
const sermons = [
 {title:'흩을 때 부해진다',date:'2026.09.27',bible:'잠언 11:24–25',seq:521152},
 {title:'약할 때 강하다',date:'2026.09.20',bible:'고린도후서 12:7–10',seq:521151},
 {title:'아버지 없이, 아버지의 것으로',date:'2026.09.13',bible:'누가복음 15:25–32',seq:521150}
];
const list = document.querySelector('#sermon-list');
function renderSermons(query='') {const found=sermons.filter(s=>(s.title+s.bible+s.date+'도원욱').includes(query.trim()));list.replaceChildren();for(const s of found){const card=document.createElement('article');card.className='sermon-card'; const small=document.createElement('small');small.textContent='주일예배 · '+s.date;const title=document.createElement('h3');title.textContent=s.title;const p=document.createElement('p');p.textContent=s.bible+' · 도원욱 목사';const a=document.createElement('a');a.href=official+'/EZ/rb/view.asp?seq='+s.seq+'&page=1&BoardModule=Media&tbcode=worship01_1';a.target='_blank';a.rel='noopener';a.innerHTML='설교 보기 <span>↗</span>';card.append(small,title,p,a);list.append(card)}document.querySelector('#search-count').textContent=query?(found.length?found.length+'개 설교':'검색 결과가 없습니다. 공식 설교 목록에서 더 찾아보세요.') : '';}
renderSermons();document.querySelector('#sermon-search').addEventListener('input',e=>renderSermons(e.target.value));
const schedules={sunday:[['1부 예배','오전 8:00','H-홀 · 워십센터 2층'],['2부 예배','오전 10:00','H-홀 · 워십센터 2층'],['3부 예배','정오 12:00','H-홀 · 워십센터 2층'],['4부 예배','오후 2:00','H-홀 · 워십센터 2층'],['5부 · 젊은이예배','오후 3:40','H-홀 · 워십센터 2층'],['6부 예배','저녁 8:00','H-홀 · 워십센터 2층']],week:[['수요오전예배','수 오전 10:30','H-홀 · 워십센터 2층'],['수요저녁예배','수 오후 7:30','H-홀 · 워십센터 2층'],['금요성령집회','금 저녁 8:50','H-홀 · 워십센터 2층'],['새벽 1부 기도회','월–금 오전 5:00','더 채플 · 비전센터 2층'],['새벽 2부 기도회','월–금 오전 6:00','H-홀 · 워십센터 2층']],next:[['영유아부 · 0–3세','10:00 / 12:00','주일 · 비전센터 3층'],['유치부 · 4–6세','10:00 / 12:00','주일 · 비전센터 3층'],['취학부 · 7–12세','10:00 / 12:00','주일 · 비전센터 1층'],['청소년부 · 13–18세','10:00 / 12:00','주일 · 비전센터 2층'],['홀리킥 사랑부','10:00 / 12:00','연령별 · 비전센터 5층']],young:[['뉴웨이브워십','토 오후 7:00','H-홀 · 워십센터 2층'],['젊은이예배','주일 오후 3:40','H-홀 · 워십센터 2층']]};
function selectTab(key){document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===key;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});const panel=document.querySelector('#schedule-panel');panel.setAttribute('aria-labelledby','tab-'+key);panel.replaceChildren();schedules[key].forEach(row=>{const div=document.createElement('div');div.className='schedule-row';['span','strong','small'].forEach((tag,i)=>{const e=document.createElement(tag);e.textContent=row[i];div.append(e)});panel.append(div)})}
selectTab('sunday');document.querySelectorAll('[data-tab]').forEach((b,i,buttons)=>{b.addEventListener('click',()=>selectTab(b.dataset.tab));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%buttons.length;if(e.key==='ArrowLeft')next=(i+buttons.length-1)%buttons.length;if(e.key==='Home')next=0;if(e.key==='End')next=buttons.length-1;if(next!==undefined){e.preventDefault();selectTab(buttons[next].dataset.tab);buttons[next].focus()}})});document.querySelectorAll('[data-tab-link]').forEach(a=>a.addEventListener('click',()=>selectTab(a.dataset.tabLink)));
const menu=document.querySelector('#menu');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');document.querySelector('#navigation').classList.toggle('open',open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('#navigation').classList.remove('open')}));
const dialog=document.querySelector('#video-dialog');document.querySelectorAll('[data-video]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#video-title').textContent=b.dataset.title;const iframe=document.createElement('iframe');iframe.src='https://www.youtube-nocookie.com/embed/'+b.dataset.video+'?autoplay=1';iframe.title=b.dataset.title;iframe.allow='autoplay; encrypted-media; picture-in-picture';iframe.allowFullscreen=true;document.querySelector('#video-frame').replaceChildren(iframe);document.querySelector('#youtube-link').href='https://www.youtube.com/watch?v='+b.dataset.video;dialog.showModal()}));document.querySelector('#close-video').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.querySelector('#video-frame').replaceChildren());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#copy-address').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('서울특별시 양천구 신정로13길 21 한성교회');document.querySelector('#copy-status').textContent='주소를 복사했습니다.'}catch{document.querySelector('#copy-status').textContent='서울특별시 양천구 신정로13길 21 — 주소를 선택해 복사해 주세요.'}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('pending');observer.observe(e)})}
